#!/usr/bin/env bash

FILE=$1;

curl \
  --silent \
  --show-error \
  --location \
  --fail \
  --dump-header /dev/fd/2 \
  --request POST \
  --upload-file "$FILE" \
  --header "Content-Type: application/json" \
  "http://localhost:8000/logs" \
